### ISSUE TITLE
IAM Role Tags

### ISSUE THREAD

**Issue by xwizzell** [aws-cloudformation/aws-cfn-lint-visual-studio-code#120]
Hello, 

When adding the Tags property to an IAM Role I get the following error. However, the template is valid and deploys just fine.  

[cfn-lint] E3002: Invalid Property Resources/ExecutionRole/Properties/Tags

Tags:
        - Key: us-regions
          Value: True

**Comment by PatMyron** [comment]
[`AWS::IAM::Role.Tags`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags) support was added last year:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/19
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

[Since the Linter itself is still separate from the Visual Studio extension](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/60), please make sure you are updating the [Linter](https://github.com/aws-cloudformation/cfn-python-lint/#install) itself separately with:
`pip3 install cfn-lint --upgrade`
