### ISSUE TITLE
Add java8.al2 as a valid AWS::Serverless::Function Runtime

### ISSUE THREAD

**Issue by danbanecker** [aws-cloudformation/aws-cfn-lint-visual-studio-code#130]
Source with the new option java8.al2
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
and
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-runtime
and
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime

**Comment by PatMyron** [comment]
[`java8.al2` support was added in August](https://github.com/aws-cloudformation/cfn-python-lint/pull/1651)

[Since the Linter itself is still separate from the Visual Studio extension](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/60), please make sure you are updating the [Linter](https://github.com/aws-cloudformation/cfn-python-lint/#install) itself separately with:
`pip3 install cfn-lint --upgrade`

**Comment by danbanecker** [comment]
Thanks!
