### ISSUE TITLE
Parameter limit changed to 200

### ISSUE THREAD

**Issue by IJsbert** [aws-cloudformation/aws-cfn-lint-visual-studio-code#153]
The limit for use of parameters is changed to 200
[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html](link)

Version 0.15.6 shows a limit of 60, see message :
[cfn-lint] E2010: The number of Parameters (62) exceeds the limit (60)

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/pull/1747

[Since the Linter itself is still separate from the Visual Studio extension](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/60), please make sure you are updating the [Linter](https://github.com/aws-cloudformation/cfn-python-lint/#install) itself separately with:
`pip3 install cfn-lint --upgrade`
